version: "3.9"

services:
    php:
        build: docker/php
        volumes:
            - ./:/app
        depends_on:
            - postgres

    postgres:
        image: postgres:16.1-alpine
        environment:
            POSTGRES_USER: symtests
            POSTGRES_PASSWORD: symtests
            POSTGRES_DB: symtests
        volumes:
            - ./docker/data/db:/var/lib/postgresql/data
        ports:
            - "15432:5432"
